apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jaeger
  template:
    metadata:
      labels:
        component: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          imagePullPolicy: Always
          ports:
              - containerPort: 5775
              - containerPort: 6831
              - containerPort: 6832
              - containerPort: 5778
              - containerPort: 16686
              - containerPort: 14268
              - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service-load
spec:
  type: LoadBalancer
  selector:
    component: jaeger
  ports:
    - protocol : TCP
      port: 80
      targetPort: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service-cluster
spec:
  type: ClusterIP
  selector:
    component: jaeger
  ports:
    - protocol : UDP
      port: 6831
      targetPort: 6831
