apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: gouravgoel44/user-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: JAEGER_HOST
          value: jaeger-service-cluster
        - name: DB_HOSTNAME
          value: mysql-service
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: config
              key: database-name
        - name: DB_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: user
  type: ClusterIP